const testData = [
	{
		"_id" : ObjectId("5c0c6e50cd6fb6c567a2a8da"),
		"title" : "building on fire",
		"description" : "large fire in region effecting following neighborhoods with smoke, neiborhood 1, 2, 3",
		"updates" : [
			"10am fire spread to next building",
			"11am fire contained"
		],
		"disasterAddress" : "",
		"disasterPinPoint" : "",
		"effectedRadius" : 5,
		"resolved" : true,
		"started" : "8am",
		"reportedBy" : "John Doe",
		"contactName" : "Bob da Builder",
		"contactPhone" : "(456) 555-6785",
		"contactEmail" : "bob@builder.com",
		"latitude" : "36",
		"longitude" : "-121",
		"radius" : "10"
	},
	{
		"_id" : ObjectId("5c1b1875da89c83c92e8c113"),
		"title" : "TEST POST!!!!!!!",
		"description" : "",
		"contactName" : "",
		"contactEmail" : "",
		"contactPhone" : "",
		"latitude" : "",
		"longitude" : "",
		"updates" : [ ]
	},
	{
		"_id" : ObjectId("5c1b18b725fc003ccf41ee66"),
		"title" : "TEST POST",
		"description" : "SOMETHING BURNING",
		"contactName" : "Joseph Richardson",
		"contactEmail" : "test@test.com",
		"contactPhone" : "5305746483"
	},
	{
		"_id" : ObjectId("5c25ac60804f3e2810c39715"),
		"title" : "",
		"description" : "",
		"contactName" : "",
		"contactEmail" : "",
		"contactPhone" : ""
	},
	{
		"_id" : ObjectId("5c268083b46d8b4ab0cf0f15"),
		"title" : "A Post",
		"description" : "With some description need to make this wider and bigger font",
		"contactName" : "name",
		"contactEmail" : "email@email.com",
		"contactPhone" : "123456",
		"updates" : [
			"Dec 28, 2018 : 11:58:26 - so far some notes",
			"Dec 28, 2018 : 11:58:36 - i guess another note"
		],
		"logitude" : "23",
		"latitude" : "23",
		"addressLine1" : "aasdsfad",
		"addressLine2" : "asdfadsf",
		"zipcode" : "23423"
	},
	{
		"_id" : ObjectId("5c26834986c4104cee055d3b"),
		"title" : "San Jose Flooding",
		"description" : "Flooding in most parts of east and south San Jose area",
		"contactName" : "Joe",
		"contactEmail" : "shmoe@email.com",
		"contactPhone" : "123456798",
		"updates" : [
			"Dec 28, 2018 : 12:10:10 - affected radius 15 miles"
		],
		"logitude" : "12",
		"latitude" : "12",
		"addressLine1" : "11",
		"addressLine2" : "12",
		"zipcode" : "123112"
	},
	{
		"_id" : ObjectId("5c380e22f0286b3c55044807"),
		"title" : "",
		"description" : "",
		"contactName" : "Hello",
		"contactEmail" : "wow@wow.com",
		"contactPhone" : "12345678",
		"updates" : [ ],
		"latitude" : "-59",
		"addressLine1" : ""
	},
	{
		"_id" : ObjectId("5c3811bdceaf22432039f723"),
		"title" : "",
		"description" : "",
		"contactName" : "Jeff",
		"contactEmail" : "test@test.com",
		"contactPhone" : "1234567890",
		"updates" : [ ],
		"latitude" : "45",
		"addressLine1" : "Test",
		"addressLine2" : "test",
		"zipcode" : "95050"
	},
	{
		"_id" : ObjectId("5c381354ecff4743d6853617"),
		"title" : "",
		"description" : "",
		"contactName" : "test",
		"contactEmail" : "test@test.com",
		"contactPhone" : "1234567890",
		"updates" : [ ],
		"longitude" : "123",
		"latitude" : "45",
		"addressLine1" : "test",
		"addressLine2" : "test",
		"zipcode" : "95050"
	},
	{
		"_id" : ObjectId("5c3826790440aa4790d58a4f"),
		"title" : "asdf",
		"description" : "sdfs",
		"contactName" : "hello",
		"contactEmail" : "hello@hello.com",
		"contactPhone" : "444-444-5555",
		"updates" : [
			"Jan 10, 2019 : 21:15:12 - asdf"
		],
		"longitude" : "-12",
		"latitude" : "44",
		"addressLine1" : "test",
		"addressLine2" : "test",
		"zipcode" : "91030"
	},
	{
		"_id" : ObjectId("5c4cf33a12c505964166f59e"),
		"title" : "Newest POst",
		"description" : "latest emergency",
		"contactName" : "Cloud Sky",
		"contactEmail" : "cloudSky@gmail.com",
		"contactPhone" : "234234234",
		"updates" : [
			"Jan 26, 2019 : 15:53:40 - something on fire",
			"Jan 26, 2019 : 15:53:53 - evacuate within 10 miles radius"
		],
		"longitude" : "78",
		"latitude" : "-50",
		"addressLine1" : "123 orak street",
		"zipcode" : "78943"
	},
	{
		"_id" : ObjectId("5c4d0702204f8499127e67a3"),
		"title" : "Life size",
		"description" : "can go big",
		"contactName" : "asdf",
		"contactEmail" : "adsf@asdf.com",
		"contactPhone" : "2342323",
		"updates" : [
			"Jan 26, 2019 : 17:18:31 - notes"
		],
		"longitude" : "12",
		"latitude" : "34",
		"addressLine1" : "2233",
		"zipcode" : "12311"
	},
	{
		"_id" : ObjectId("5c4d09b99c32089a47d1e03c"),
		"title" : "Abscract Fire",
		"description" : "other students hw",
		"contactName" : "asdf",
		"contactEmail" : "asdf@asdf.com",
		"contactPhone" : "2323323",
		"updates" : [
			"Jan 26, 2019 : 17:29:54 - wwwww"
		],
		"longitude" : "12",
		"latitude" : "11",
		"addressLine1" : "asdfa",
		"addressLine2" : "asdfasf",
		"zipcode" : "232323"
	},
	{
		"_id" : ObjectId("5c56242c6437f056f111a157"),
		"title" : "building on fire",
		"description" : "large fire in region effecting following neighborhoods with smoke, neiborhood 1, 2, 3",
		"contactName" : "Bob da Builder",
		"contactEmail" : "bob@builder.com",
		"contactPhone" : "(456) 555-6785",
		"updates" : [
			"10am fire spread to next building",
			"11am fire contained"
		],
		"longitude" : "-121",
		"latitude" : "36",
		"radius" : "10"
	},
	{
		"_id" : ObjectId("5cadb3ce1b1ed4fcd6af783f"),
		"title" : "",
		"description" : "",
		"updates" : [ ],
		"updateItem" : "",
		"contactName" : "",
		"contactEmail" : "",
		"contactPhone" : "",
		"addressLine1" : "",
		"addressLine2" : "",
		"zipcode" : "",
		"longitude" : "",
		"latitude" : "",
		"radius" : ""
	},
	{
		"_id" : ObjectId("5cadb3cf1b1ed4fcd6af7840"),
		"title" : "",
		"description" : "",
		"updates" : [ ],
		"updateItem" : "",
		"contactName" : "",
		"contactEmail" : "",
		"contactPhone" : "",
		"addressLine1" : "",
		"addressLine2" : "",
		"zipcode" : "",
		"longitude" : "",
		"latitude" : "",
		"radius" : ""
	},
	{
		"_id" : ObjectId("5cadb3d01b1ed4fcd6af7841"),
		"title" : "",
		"description" : "",
		"updates" : [ ],
		"updateItem" : "",
		"contactName" : "",
		"contactEmail" : "",
		"contactPhone" : "",
		"addressLine1" : "",
		"addressLine2" : "",
		"zipcode" : "",
		"longitude" : "",
		"latitude" : "",
		"radius" : ""
	},
	{
		"_id" : ObjectId("5cadb3d11b1ed4fcd6af7842"),
		"title" : "",
		"description" : "",
		"updates" : [ ],
		"updateItem" : "",
		"contactName" : "",
		"contactEmail" : "",
		"contactPhone" : "",
		"addressLine1" : "",
		"addressLine2" : "",
		"zipcode" : "",
		"longitude" : "",
		"latitude" : "",
		"radius" : ""
	},
	{
		"_id" : ObjectId("5cadb3fca48bdafcf18a3fda"),
		"title" : "",
		"description" : "",
		"updates" : [ ],
		"updateItem" : "",
		"contactName" : "",
		"contactEmail" : "",
		"contactPhone" : "",
		"addressLine1" : "",
		"addressLine2" : "",
		"zipcode" : "",
		"longitude" : "",
		"latitude" : "",
		"radius" : ""
	},
	{
		"_id" : ObjectId("5cadb54658da09fd5329a3d6"),
		"title" : "",
		"description" : "",
		"updates" : [ ],
		"updateItem" : "",
		"contactName" : "",
		"contactEmail" : "",
		"contactPhone" : "",
		"addressLine1" : "",
		"addressLine2" : "",
		"zipcode" : "",
		"longitude" : "",
		"latitude" : "",
		"radius" : ""
	},
	{
		"_id" : ObjectId("5cadb55358da09fd5329a3d7"),
		"title" : "",
		"description" : "",
		"updates" : [ ],
		"updateItem" : "",
		"contactName" : "",
		"contactEmail" : "",
		"contactPhone" : "",
		"addressLine1" : "",
		"addressLine2" : "d",
		"zipcode" : "",
		"longitude" : "",
		"latitude" : "",
		"radius" : ""
	},
	{
		"_id" : ObjectId("5caec4e168a3936a13f4bfc6"),
		"title" : "Testing Errors",
		"description" : "Wow",
		"updates" : [
			"Apr 10, 2019 : 21:37:35 - This is an update"
		],
		"updateItem" : "",
		"contactName" : "John Doe",
		"contactEmail" : "jdoe@test.com",
		"contactPhone" : "(123) 455-4238",
		"addressLine1" : "123 Street",
		"addressLine2" : "",
		"zipcode" : "91106",
		"longitude" : "-123.34",
		"latitude" : "34.12",
		"radius" : "6"
	},
	{
		"_id" : ObjectId("5cb0075cd41bdc3e324539a2"),
		"title" : "A disaster",
		"description" : "A very bad fire",
		"updates" : [ ],
		"updateItem" : "asdf",
		"contactName" : "kevin",
		"contactEmail" : "kevin@gmail.com",
		"contactPhone" : "388903232",
		"addressLine1" : "123 Fake Street",
		"addressLine2" : "",
		"zipcode" : "90210",
		"longitude" : "-124",
		"latitude" : "34",
		"radius" : ""
	},
	{
		"_id" : ObjectId("5cb00761d41bdc3e324539a3"),
		"title" : "A disaster",
		"description" : "A very bad fire",
		"updates" : [ ],
		"updateItem" : "asdf",
		"contactName" : "kevin",
		"contactEmail" : "kevin@gmail.com",
		"contactPhone" : "388903232",
		"addressLine1" : "123 Fake Street",
		"addressLine2" : "",
		"zipcode" : "90210",
		"longitude" : "-124",
		"latitude" : "34",
		"radius" : "77"
	},
	{
		"_id" : ObjectId("5cb00769d41bdc3e324539a4"),
		"title" : "A disaster",
		"description" : "A very bad fire",
		"updates" : [ ],
		"updateItem" : "asdf",
		"contactName" : "kevin",
		"contactEmail" : "kevin@gmail.com",
		"contactPhone" : "388903232",
		"addressLine1" : "123 Fake Street",
		"addressLine2" : "",
		"zipcode" : "90210",
		"longitude" : "-124",
		"latitude" : "34",
		"radius" : "10"
	},
	{
		"_id" : ObjectId("5cb00775d41bdc3e324539a5"),
		"title" : "A disaster",
		"description" : "A very bad fire",
		"updates" : [ ],
		"updateItem" : "asdf",
		"contactName" : "kevin",
		"contactEmail" : "kevin@gmail.com",
		"contactPhone" : "388903232",
		"addressLine1" : "123 Fake Street",
		"addressLine2" : "",
		"zipcode" : "90210",
		"longitude" : "-124",
		"latitude" : "34",
		"radius" : "10"
	},
	{
		"_id" : ObjectId("5cb007abd41bdc3e324539a6"),
		"title" : "A disaster",
		"description" : "A very bad fire",
		"updates" : [ ],
		"updateItem" : "asdf",
		"contactName" : "kevin",
		"contactEmail" : "kevin@gmail.com",
		"contactPhone" : "388903232",
		"addressLine1" : "123 Fake Street",
		"addressLine2" : "",
		"zipcode" : "90210",
		"longitude" : "-124",
		"latitude" : "34",
		"radius" : "10"
	},
	{
		"_id" : ObjectId("5cb007acd41bdc3e324539a7"),
		"title" : "A disaster",
		"description" : "A very bad fire",
		"updates" : [ ],
		"updateItem" : "asdf",
		"contactName" : "kevin",
		"contactEmail" : "kevin@gmail.com",
		"contactPhone" : "388903232",
		"addressLine1" : "123 Fake Street",
		"addressLine2" : "",
		"zipcode" : "90210",
		"longitude" : "-124",
		"latitude" : "34",
		"radius" : "10"
	},
	{
		"_id" : ObjectId("5d3a90bf66033902ae4f059e"),
		"title" : "Radioactive HazMat Breach",
		"description" : "Workers were removing cesium chloride salt from Regional Medical Center when the breach occurred.",
		"updates" : [
			"Jul 25, 2019 : 22:29:02 - 13 people have tested positive for exposure to radioactive materials so far"
		],
		"updateItem" : "",
		"contactName" : "Aaron Hill",
		"contactEmail" : "ahill@gmail.com",
		"contactPhone" : "(408) 259-8579",
		"addressLine1" : "225 North Jackson Ave",
		"addressLine2" : "",
		"zipcode" : "95116",
		"longitude" : "37",
		"latitude" : "-121",
		"radius" : "3"
	},
	{
		"_id" : ObjectId("5d3a90d066033902ae4f059f"),
		"title" : "Radioactive HazMat Breach",
		"description" : "Workers were removing cesium chloride salt from Regional Medical Center when the breach occurred.",
		"updates" : [
			"Jul 25, 2019 : 22:29:02 - 13 people have tested positive for exposure to radioactive materials so far"
		],
		"updateItem" : "",
		"contactName" : "Aaron Hill",
		"contactEmail" : "ahill@gmail.com",
		"contactPhone" : "(408) 259-8579",
		"addressLine1" : "225 North Jackson Ave",
		"addressLine2" : "",
		"zipcode" : "95116",
		"longitude" : "-121",
		"latitude" : "37",
		"radius" : "3"
	},
	{
		"_id" : ObjectId("5d3a90e166033902ae4f05a0"),
		"title" : "Radioactive HazMat Breach",
		"description" : "Workers were removing cesium chloride salt from Regional Medical Center when the breach occurred.",
		"updates" : [
			"Jul 25, 2019 : 22:29:02 - 13 people have tested positive for exposure to radioactive materials so far"
		],
		"updateItem" : "",
		"contactName" : "Aaron Hill",
		"contactEmail" : "ahill@gmail.com",
		"contactPhone" : "(408) 259-8579",
		"addressLine1" : "225 North Jackson Ave",
		"addressLine2" : "",
		"zipcode" : "95116",
		"longitude" : "-121",
		"latitude" : "37",
		"radius" : "3"
	}
]